name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *' # everyday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: liuwd15
          base: main
          head: main
